# https://mshr-h.com/posts/new-website-with-hugo/

baseURL = 'https://www.pyonkichi369.com/'
canonifyurls = true
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'PYONKICHI BLOG'
theme = 'hugo-PaperMod'
publishDir = 'docs'
searchHidden = false
enableEmoji = true

[author]
  name = "ã´ã‚‡ã‚“ãã¡"
  bio = "ã‚µãƒ³ãƒ—ãƒ«"
  job = "enginner"
  location = "Japan"
  picture = "images/thumbnail.jpg"
  gravatarEmail = "belle.official369@gmail.com"

[languages]
  [languages.ja]
      title = 'ã´ã‚‡ã‚“ãã¡ãƒ–ãƒ­ã‚°'
      languageName = 'ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª'
      displayFullLangName = true
      weight = 1
      [languages.ja.params.homeInfoParams]
        title = "ã“ã‚“ã«ã¡ã¯ ğŸ‘‹"
        content = "ã¨ãƒ¼ãã‚‡ãƒ¼ã§ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã—ã¦ã¾ã™"
  [languages.en]
      title = 'PYONKICHI BLOG'
      languageName = 'ğŸ‡ºğŸ‡¸ English'
      displayFullLangName = true
      weight = 2
      [languages.en.params.homeInfoParams]
        title = "Hi there ğŸ‘‹"
        content = "A Software Engineer @Tokyo "

[params]
  sidebarBehavior = 2
  thumbnailImage = true
  dateFormat = "2006-01-02"
  thumbnailImagePosition = "left"
  autoThumbnailImage = true
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = "highlight.js"
  showShareButtons = true
  showBreadCrumbs = true
  showPostNavLinks = true
  showReadingTime = true
  showCodeCopyButtons = true
  comments = true

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "HOME"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "about"
  name = "ABOUT"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/about"
[[menu.main]]
  weight = 3
  identifier = "categories"
  name = "CATEGORIES"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 4
  identifier = "tags"
  name = "TAGS"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 5
  identifier = "search"
  name = "SEARCH"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/search"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = "https://github.com/kakawait"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/pyonkichi369/"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/pyonkichi369/"

[[params.socialIcons]]
  name = "email"
  url = "mailto:belle.official369@gmail.com"

[[params.socialIcons]]
  name = "rss"
  url = "index.xml"

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
